version: '3'
services:
  nuxt:
    # Build the Nuxt application using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      # Database connection string for Pruvious
      - NUXT_PRUVIOUS_DATABASE=postgresql://pruvious:pruvious@db:5432/pruvious
    volumes:
      # Mount point for uploads. Replace <PATH_TO_UPLOADS> with your desired local path
      - <PATH_TO_UPLOADS>:/app/uploads
    ports:
      # Expose the Nuxt application on port 3000
      - 3000:3000
  db:
    image: postgres:16-alpine
    restart: always
    # Uncomment the following line to use a custom PostgreSQL configuration file
    # command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    environment:
      - POSTGRES_USER=pruvious
      - POSTGRES_PASSWORD=pruvious
      - POSTGRES_DB=pruvious
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      # Mount point for PostgreSQL data. Replace <PATH_TO_DB_DATA> with your desired local path
      - <PATH_TO_DB_DATA>:/var/lib/postgresql/data/
    ports:
      # Expose PostgreSQL on port 5432
      - 5432:5432
